[server]
headless = true
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 50
fileWatcherType = "none"

[browser]
gatherUsageStats = false

[client]
showErrorDetails = "none"
toolbarMode = "minimal"

[theme]
base = "light"
primaryColor = "#0F766E"
